<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Bài_1_Tạo_form_và_sử_dụng_các_thuộc_tính_mở_rộng_trên_form</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\image\" />
  </ItemGroup>

</Project>
